services:
  - type: web
    name: prismatique-api
    env: node
    plan: free
    buildCommand: "npm install"
    startCommand: "node api.js"
    envVars:
      - key: NODE_ENV
        value: production
